### ISSUE TITLE
Error while creating new user

### ISSUE THREAD

**Issue by amrutakamat16** [airavata-courses/TeamZenith#40] opened 2016-04-04 05:32 UTC
Getting below page on creating new user. The user gets created but login page redirects me to below page:

![error](https://cloud.githubusercontent.com/assets/16785989/14238973/07bcb8ce-fa05-11e5-9ad1-350fb2084cfc.png)

**Comment by anujbhan** [comment] 2016-04-05 01:44
duplicate of #36, closing the issue

**Closed as completed by anujbhan** 2016-04-05 01:44 UTC
