### ISSUE TITLE
could not configure web application.

### ISSUE THREAD

**Issue by ajinkya-dhamnaskar** [airavata-courses/TeamZenith#33] opened 2016-03-30 04:41 UTC
Hello,

I followed the instructions but somehow not able to get through. As described I should be able to access application without context name as we are deploying it in root directory. Catalina listed few errors regarding stormpath while starting the server.

Please help me with the same.

**Comment by anujbhan** [comment] 2016-03-30 04:45
Yes Ajinkya, this issue has already been addressed for, send me your email ID, I will mail a api key with instructions. the instructions are also given out in instruction file. Closing this issue as the duplicate of #32 . Thanks for the heads up.

**Closed as completed** 2016-03-30 04:45 UTC
